const express = require('express');
const path = require("path");
const cookieParser = require('cookie-parser');
const https = require('https');
const fs = require('fs');
require('dotenv').config();

const { connectMongoDB } = require("./connection");
const verifyJWT = require('./middleware/verifyJWT');

const startTokenCleanupJob = require('./middleware/cornJob');

// --- REQUIRE ROUTERS ---

// Auth Routers
const login = require('./routes/login');       
const refresh = require('./routes/refresh'); 
const logout = require('./routes/logOut');   
const forgotPassword = require('./routes/forgotPassword');

// Feature Routers
const home = require('./routes/homePageAPIs');
const user = require('./routes/user');
const subject = require('./routes/subject');
const marks = require('./routes/marks');
const coPoMapping = require('./routes/coPoMapping');
const assignSubject = require('./routes/assignSubject');
const uploadAllAssignSubjects = require('./routes/uploadAllAssignSubjects');
const calculatedPo = require('./routes/calculatedPo');
const directAttainemt = require('./routes/directAttainemt');
const uploadAllSubjects = require('./routes/uploadAllSubjects');
const uploadRubrics = require('./routes/rubrics');
const downloadReport = require('./routes/downloadReport');
const downloadDirectAttainmentReport = require('./routes/downloadDirectAttainmentReport');
const formatDownload = require('./routes/formatDownload');
const activity = require('./routes/activities');
const subjectAnalysis = require('./routes/subjectAnalysis');

const app = express();
const PORT = process.env.PORT || 3000;
const mongoUri = process.env.MONGO_URI;

// Grab the IP from the .env file (fallback to localhost if missing)
const hostIp = process.env.HOST_IP || 'localhost';

// --- GLOBAL MIDDLEWARES ---
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
app.use(cookieParser()); // Must be before your routes to read the refresh token cookie

// View engine setup
app.set('view engine', "ejs");
app.set("views", path.resolve("./view"));

// --- DATABASE CONNECTION ---
connectMongoDB(mongoUri)
    .then(() => console.log("MongoDB Connected!"))
    .catch((err) => console.log("Error: ", err));

// 1. PUBLIC ROUTES (Accessible to anyone)
app.use("/login", login);
app.use("/refresh", refresh);
app.use("/logout", logout);
app.use("/", forgotPassword);

// 2. JWT VERIFICATION GATEWAY
// Any route below this line will require a valid Access Token
app.use(verifyJWT);

// 3. PROTECTED ROUTES (Requires valid login)
app.use("/home", home);
app.use("/user", user);
app.use("/sub", subject);
app.use("/mark", marks);
app.use("/co-po", coPoMapping);
app.use("/assignSub", assignSubject);
app.use("/sub-upload", uploadAllAssignSubjects);
app.use("/calpo", calculatedPo);
app.use("/dir", directAttainemt);
app.use("/uploadAll", uploadAllSubjects);
app.use("/rubrics", uploadRubrics);
app.use("/file", downloadReport);
app.use("/report", downloadDirectAttainmentReport);
app.use("/download-format", formatDownload);
app.use("/activity", activity);
app.use("/subject-analysis", subjectAnalysis);

startTokenCleanupJob();

// --- HTTPS SERVER SETUP ---

// Load the local SSL certificates generated by mkcert
const httpsOptions = {
  key: fs.readFileSync('./local-key.pem'),
  cert: fs.readFileSync('./local-cert.pem')
};

// Start the HTTPS server listening on all network interfaces ('0.0.0.0')
https.createServer(httpsOptions, app).listen(PORT, '0.0.0.0', () => {
    console.log(`Secure Server Started at https://${hostIp}:${PORT}`);
});






























































// const express = require('express');
// const path = require("path");
// const cookieParser = require('cookie-parser');
// const https = require('https'); // <-- ADD THIS
// const fs = require('fs');
// require('dotenv').config();

// const { connectMongoDB } = require("./connection");
// const verifyJWT = require('./middleware/verifyJWT');

// const startTokenCleanupJob = require('./middleware/cornJob');

// // --- REQUIRE ROUTERS ---

// // Auth Routers (New ones we talked about)
// const login = require('./routes/login');       // Contains handleLogin
// const refresh = require('./routes/refresh'); // Contains handleRefreshToken
// const logout = require('./routes/logOut');   // Contains handleLogout
// const forgotPassword = require('./routes/forgotPassword');

// // Feature Routers (Your existing ones)
// const home = require('./routes/homePageAPIs');
// const user = require('./routes/user');
// const subject = require('./routes/subject');
// const marks = require('./routes/marks');
// const coPoMapping = require('./routes/coPoMapping');
// const assignSubject = require('./routes/assignSubject');
// const uploadAllAssignSubjects = require('./routes/uploadAllAssignSubjects');
// const calculatedPo = require('./routes/calculatedPo');
// const directAttainemt = require('./routes/directAttainemt');
// const uploadAllSubjects = require('./routes/uploadAllSubjects');
// const uploadRubrics = require('./routes/rubrics');
// const downloadReport = require('./routes/downloadReport');
// const downloadDirectAttainmentReport = require('./routes/downloadDirectAttainmentReport');
// const formatDownload = require('./routes/formatDownload');
// const activity = require('./routes/activities');
// const subjectAnalysis = require('./routes/subjectAnalysis');



// const app = express();
// const PORT = process.env.PORT || 3000;
// const mongoUri = process.env.MONGO_URI;

// // --- GLOBAL MIDDLEWARES ---
// app.use(express.json());
// app.use(express.urlencoded({ extended: true }));
// app.use(express.static(path.join(__dirname, 'public')));
// app.use(cookieParser()); // Must be before your routes to read the refresh token cookie

// // View engine setup
// app.set('view engine', "ejs");
// app.set("views", path.resolve("./view"));

// // --- DATABASE CONNECTION ---
// connectMongoDB(mongoUri)
//     .then(() => console.log("MongoDB Connected!"))
//     .catch((err) => console.log("Error: ", err));


// // 1. PUBLIC ROUTES (Accessible to anyone)

// app.use("/login", login);
// app.use("/refresh", refresh);
// app.use("/logout", logout);
// app.use("/", forgotPassword);

// // 2. JWT VERIFICATION GATEWAY

// // Any route below this line will require a valid Access Token
// app.use(verifyJWT);


// // 3. PROTECTED ROUTES (Requires valid login)

// app.use("/home", home);
// app.use("/user", user);
// app.use("/sub", subject);
// app.use("/mark", marks);
// app.use("/co-po", coPoMapping);
// app.use("/assignSub", assignSubject);
// app.use("/sub-upload", uploadAllAssignSubjects);
// app.use("/calpo", calculatedPo);
// app.use("/dir", directAttainemt);
// app.use("/uploadAll", uploadAllSubjects);
// app.use("/rubrics", uploadRubrics);
// app.use("/file", downloadReport);
// app.use("/report", downloadDirectAttainmentReport);
// app.use("/download-format", formatDownload);
// app.use("/activity", activity);
// app.use("/subject-analysis", subjectAnalysis);


// startTokenCleanupJob();

// // app.listen(PORT, () => {
// //     console.log(`Server Started at PORT: ${PORT}`);
// // });


// // Load the local SSL certificates
// const httpsOptions = {
//   key: fs.readFileSync('./192.168.1.101-key.pem'),
//   cert: fs.readFileSync('./192.168.1.101.pem')
// };

// // Start the HTTPS server listening on all network interfaces ('0.0.0.0')
// https.createServer(httpsOptions, app).listen(PORT, '0.0.0.0', () => {
//     console.log(`Secure Server Started at https://192.168.1.101:${PORT}`);
// });